name: fusionneur
description: "Application de concaténation de projet pour travailler avec des IA. Inclus un manifest et un JSON index"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  flutter_riverpod: ^3.0.0
  path: ^1.7.0
  file_picker: ^10.3.3
  crypto: ^3.0.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true


